### ISSUE TITLE
function `fs-svg` should accept a function as an argument 

### ISSUE THREAD

**Issue by matbrady** [Threespot/frontline-sass#10]
Would be convienent if `fs-svg` accepted a function for the `$color` arguement.

**Use Case**:

```scss
.example {
  background-image: url( fs-svg($name: 'chevron', $color: fs-color('blue') ) );
}
```

**Pseudo**:
```scss
@function fs-svg($name, $color) {
  // . . .
  // Fill
  $fill: '';
  @if ($color) {
    @if (type-of($color) == 'function') {
      $fill: call($color);
    } @else {
      $fill: ' fill="#{$color}"';
    }
  }
  // . . . 
}
```
